databases:
  - name: cinedb
    plan: free
    databaseName: cine
    user: cine

services:
  - type: web
    plan: free
    name: cine
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn cine.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4